<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.5">
  <POU Name="REC_Queue" Id="{832394c0-1517-48e2-8c89-b76fea609dd7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK REC_Queue
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Count_Queue" Id="{686262fd-2396-4462-81b8-5b181d3f2c6f}">
      <Declaration><![CDATA[METHOD Count_Queue
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Delete_Queue" Id="{55ded70a-c88b-47b8-bb22-6533aafbb848}">
      <Declaration><![CDATA[METHOD Delete_Queue
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Empty_Queue" Id="{4a105195-4dd5-475c-bf44-a3e7dc5552da}">
      <Declaration><![CDATA[METHOD Empty_Queue
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Full_Queue" Id="{5cec573b-8d8a-436c-9c16-db07a6ea5440}">
      <Declaration><![CDATA[METHOD Full_Queue
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Head_Queue" Id="{fd96c293-b0fd-47cf-8959-99c3b5a08f6b}">
      <Declaration><![CDATA[METHOD Head_Queue
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Init_Queue" Id="{e62adc94-f1a3-4959-86d8-40a71887af54}">
      <Declaration><![CDATA[METHOD Init_Queue
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Insert_Queue" Id="{82e0b24e-c50c-4ed1-a77e-80a5926b03f4}">
      <Declaration><![CDATA[METHOD Insert_Queue
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>